exports.msgEnum = {
  EMAIL_EXISTED: "Email already exists",
  MISSING_EMAIL: "Missing email address",
  USER_NOT_EXIST: "User does not exist",
  USER_INACTIVATED: "User does not activated",
  MISSING_LOGIN_DATA: "Missing username or password",
  INCORRECT_PASSWORD: "Password is incorrect",
  SEND_OTP_SUCCESS: "otp code has been sent",
  MISSING_TOKEN: "Missing token",
  TOKEN_EXPIRED: "token has expired",
  NOT_FOUND: "Not found",
  INVALID_TOKEN: "Invalid token",
  LOGGED_OUT: "Logged out",
  RESET_PASSWORD_SUCCESS: "Reset password success",
  // DUPLICATE_VALUE: "Data has been duplicated",
  DUPLICATE_VALUE: "has been duplicated",
  CREATE_POST_SUCCESS: "Create post successfully",
  DELETE_POST_SUCCESS: "Delete post successfully",
  UPDATE_POST_SUCCESS: "Update post successfully",
  POST_NOT_EXIST: "Post does not exist",
  NO_PERMISSION: "No permission",
  NO_FILE_UPLOADED: "No file uploaded",
  MISSING_FAVORITE_DATA: "Missing post(id)",
};
