exports.msgEnum = {
  LOGIN_SUCCESS: "Đăng nhập thành công",
  LOGIN_FAIL: "Đăng nhập thất bại",
  REGISTER_SUCCESS: "Đăng ký thành công",
  FORM_REGISTER_INVALID: "Đăng ký thất bại",
  MAIL_SENT: "Liên kết đặt lại mật khẩu đã được gửi đến email của bạn",
  RESET_PASSWORD_SUCCESS: "Khôi phục mật khẩu thành công",
  RESET_PASSWORD_FAIL: "Mã không hợp lệ",
  CHANGE_PASSWORD_SUCCESS: "Đổi mật khẩu thành công",
  CREATE_SUCCESS: "Thêm thành công",
  CREATE_FAIL: "Thêm thất bại",
  DELETE_SUCCESS: "Xóa thành công",
  DELETE_FAIL: "Xóa thất bại",
  UPLOAD_SUCCESS: "Upload thành công",
  WRONG_FILE_TYPE: "Định dạng tệp tin không được phép tải lên",
  FILE_SIZE_OVER: "Kích thước tệp tin vượt quá quy định",
  UPLOAD_FAIL: "Tải lên thất bại",
  SERVER_ERROR: "Lỗi máy chủ",
  DUPLICATE_VALUE: "Trùng dữ liệu",
  DATA_NOT_FOUND: "Không tìm thấy dữ liệu",
  TOKEN_INVALID: "Token không hợp lệ",
  ACCESS_TOKEN_NOT_FOUND: "Không tìm thấy access token",
  REFRESH_TOKEN_NOT_FOUND: "Không tìm thấy refresh token",
  UPDATE_SUCCESS: "Cập nhật thành công",
  USER_NOT_FOUND: "Người dùng không tồn tại",
  WRONG_PASSWORD: "Mật khẩu không đúng",
  NOT_PERMISSION_DELETE: "Không được phép xóa",
  FAIL_FORMAT: "Dữ liệu không đúng định dạng",
  UNAUTHORIZED: "Chưa được xác thực",
  UPDATE_FAIL: "Cập nhật không thành công",
  WRONG_CONFIRM_PASSWORD: "Xác nhận mật khẩu không đúng",
  LOGGED_OUT: "Đăng xuất thành công",
  CAST_ERROR: "Cast Error: sai định dạng _id",
};
